# Generated by Django 6.1 on 2026-09-06 10:08

import app.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", app.users.models.UnboundedCharField()),
                (
                    "first_name",
                    app.users.models.UnboundedCharField(blank=True, null=True),
                ),
                (
                    "last_name",
                    app.users.models.UnboundedCharField(blank=True, null=True),
                ),
                ("hashed_password", app.users.models.UnboundedCharField()),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("is_superuser", models.BooleanField(default=False, null=True)),
            ],
            options={
                "db_table": "user",
                "indexes": [models.Index(fields=["id"], name="ix_user_id")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email",), name="ix_user_email"
                    )
                ],
            },
        ),
    ]
